[2025-01-28 00:00:39,413] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-405d871f-7c9b-44c0-9cee-3396b9e39e38 in group yolov8-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:00:39,414] INFO [GroupCoordinator 0]: Preparing to rebalance group yolov8-group in state PreparingRebalance with old generation 3 (__consumer_offsets-35) (reason: removing member kafka-python-2.0.2-405d871f-7c9b-44c0-9cee-3396b9e39e38 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:00:39,414] INFO [GroupCoordinator 0]: Group yolov8-group with generation 4 is now empty (__consumer_offsets-35) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:01:17,098] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group yolov8-group in Empty state. Created a new member id kafka-python-2.0.2-85b46bf2-0f86-4d88-a8d0-6b860d9838a0 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:01:17,098] INFO [GroupCoordinator 0]: Preparing to rebalance group yolov8-group in state PreparingRebalance with old generation 4 (__consumer_offsets-35) (reason: Adding new member kafka-python-2.0.2-85b46bf2-0f86-4d88-a8d0-6b860d9838a0 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:01:17,099] INFO [GroupCoordinator 0]: Stabilized group yolov8-group generation 5 (__consumer_offsets-35) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:01:17,101] INFO [GroupCoordinator 0]: Assignment received from leader for group yolov8-group for generation 5. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:09:44,616] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-85b46bf2-0f86-4d88-a8d0-6b860d9838a0 in group yolov8-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:09:44,616] INFO [GroupCoordinator 0]: Preparing to rebalance group yolov8-group in state PreparingRebalance with old generation 5 (__consumer_offsets-35) (reason: removing member kafka-python-2.0.2-85b46bf2-0f86-4d88-a8d0-6b860d9838a0 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:09:44,617] INFO [GroupCoordinator 0]: Group yolov8-group with generation 6 is now empty (__consumer_offsets-35) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:15:27,246] INFO Creating topic input-topic with configuration {} and initial partition assignment HashMap(0 -> ArrayBuffer(0)) (kafka.zk.AdminZkClient)
[2025-01-28 00:15:27,297] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(input-topic-0) (kafka.server.ReplicaFetcherManager)
[2025-01-28 00:15:27,300] INFO [Log partition=input-topic-0, dir=/tmp/kafka-logs] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
[2025-01-28 00:15:27,301] INFO Created log for partition input-topic-0 in /tmp/kafka-logs/input-topic-0 with properties {compression.type -> producer, min.insync.replicas -> 1, message.downconversion.enable -> true, segment.jitter.ms -> 0, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, retention.ms -> 604800000, segment.bytes -> 1073741824, flush.messages -> 9223372036854775807, message.format.version -> 2.8-IV1, max.compaction.lag.ms -> 9223372036854775807, file.delete.delay.ms -> 60000, max.message.bytes -> 1048588, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, preallocate -> false, index.interval.bytes -> 4096, min.cleanable.dirty.ratio -> 0.5, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, segment.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760}. (kafka.log.LogManager)
[2025-01-28 00:15:27,302] INFO [Partition input-topic-0 broker=0] No checkpointed highwatermark is found for partition input-topic-0 (kafka.cluster.Partition)
[2025-01-28 00:15:27,302] INFO [Partition input-topic-0 broker=0] Log loaded for partition input-topic-0 with initial high watermark 0 (kafka.cluster.Partition)
[2025-01-28 00:18:34,577] INFO Creating topic output-topic with configuration {} and initial partition assignment HashMap(0 -> ArrayBuffer(0)) (kafka.zk.AdminZkClient)
[2025-01-28 00:18:34,600] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(output-topic-0) (kafka.server.ReplicaFetcherManager)
[2025-01-28 00:18:34,602] INFO [Log partition=output-topic-0, dir=/tmp/kafka-logs] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
[2025-01-28 00:18:34,602] INFO Created log for partition output-topic-0 in /tmp/kafka-logs/output-topic-0 with properties {compression.type -> producer, min.insync.replicas -> 1, message.downconversion.enable -> true, segment.jitter.ms -> 0, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, retention.ms -> 604800000, segment.bytes -> 1073741824, flush.messages -> 9223372036854775807, message.format.version -> 2.8-IV1, max.compaction.lag.ms -> 9223372036854775807, file.delete.delay.ms -> 60000, max.message.bytes -> 1048588, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, preallocate -> false, index.interval.bytes -> 4096, min.cleanable.dirty.ratio -> 0.5, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, segment.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760}. (kafka.log.LogManager)
[2025-01-28 00:18:34,603] INFO [Partition output-topic-0 broker=0] No checkpointed highwatermark is found for partition output-topic-0 (kafka.cluster.Partition)
[2025-01-28 00:18:34,603] INFO [Partition output-topic-0 broker=0] Log loaded for partition output-topic-0 with initial high watermark 0 (kafka.cluster.Partition)
[2025-01-28 00:23:15,155] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-30658 in state PreparingRebalance with old generation 0 (__consumer_offsets-33) (reason: Adding new member consumer-console-consumer-30658-1-622d1117-011d-494d-b5a0-09645a3fa7d4 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:23:15,155] INFO [GroupCoordinator 0]: Stabilized group console-consumer-30658 generation 1 (__consumer_offsets-33) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:23:15,158] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-30658 for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:44:57,406] INFO Unable to read additional data from server sessionid 0x100009acc3e0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:44:57,657] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2025-01-28 00:44:57,658] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2025-01-28 00:44:57,659] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2025-01-28 00:44:58,820] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:44:58,820] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:44:58,924] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2025-01-28 00:44:59,570] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-30658-1-622d1117-011d-494d-b5a0-09645a3fa7d4] in group console-consumer-30658 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:44:59,571] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-30658 in state PreparingRebalance with old generation 1 (__consumer_offsets-33) (reason: removing member consumer-console-consumer-30658-1-622d1117-011d-494d-b5a0-09645a3fa7d4 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:44:59,571] INFO [GroupCoordinator 0]: Group console-consumer-30658 with generation 2 is now empty (__consumer_offsets-33) (kafka.coordinator.group.GroupCoordinator)
[2025-01-28 00:45:00,866] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:00,867] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:02,320] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:02,321] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:04,021] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:04,021] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:05,300] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:05,300] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:06,866] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:06,866] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:08,756] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:08,756] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:10,102] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:10,102] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:12,115] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:12,116] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:13,813] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:13,814] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:15,669] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:15,669] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:17,216] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:17,216] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:18,017] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2025-01-28 00:45:18,652] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:18,653] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:20,726] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:20,726] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:22,036] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-28 00:45:22,036] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
